twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        auteur: '%env(APP_AUTHOR)%'
    form_themes:    ['bootstrap_4_layout.html.twig']
    paths:
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator
        '%kernel.project_dir%/vendor/knplabs/knp-menu-bundle/src/Resources/views': KnpMenu
